/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as CorridorsRouteImport } from './routes/corridors'
import { Route as FieldReportsRouteImport } from './routes/field-reports'
import { Route as RouteEngineRouteImport } from './routes/route-engine'
import { Route as SupplyRouteImport } from './routes/supply'
import { Route as VehiclesRouteImport } from './routes/vehicles'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const CorridorsRoute = CorridorsRouteImport.update({
  id: '/corridors',
  path: '/corridors',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldReportsRoute = FieldReportsRouteImport.update({
  id: '/field-reports',
  path: '/field-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteEngineRoute = RouteEngineRouteImport.update({
  id: '/route-engine',
  path: '/route-engine',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplyRoute = SupplyRouteImport.update({
  id: '/supply',
  path: '/supply',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/alerts': typeof AlertsRoute
  '/corridors': typeof CorridorsRoute
  '/field-reports': typeof FieldReportsRoute
  '/route-engine': typeof RouteEngineRoute
  '/supply': typeof SupplyRoute
  '/vehicles': typeof VehiclesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/alerts': typeof AlertsRoute
  '/corridors': typeof CorridorsRoute
  '/field-reports': typeof FieldReportsRoute
  '/route-engine': typeof RouteEngineRoute
  '/supply': typeof SupplyRoute
  '/vehicles': typeof VehiclesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/alerts': typeof AlertsRoute
  '/corridors': typeof CorridorsRoute
  '/field-reports': typeof FieldReportsRoute
  '/route-engine': typeof RouteEngineRoute
  '/supply': typeof SupplyRoute
  '/vehicles': typeof VehiclesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibility'
    | '/alerts'
    | '/corridors'
    | '/field-reports'
    | '/route-engine'
    | '/supply'
    | '/vehicles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibility'
    | '/alerts'
    | '/corridors'
    | '/field-reports'
    | '/route-engine'
    | '/supply'
    | '/vehicles'
  id:
    | '__root__'
    | '/'
    | '/accessibility'
    | '/alerts'
    | '/corridors'
    | '/field-reports'
    | '/route-engine'
    | '/supply'
    | '/vehicles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AlertsRoute: typeof AlertsRoute
  CorridorsRoute: typeof CorridorsRoute
  FieldReportsRoute: typeof FieldReportsRoute
  RouteEngineRoute: typeof RouteEngineRoute
  SupplyRoute: typeof SupplyRoute
  VehiclesRoute: typeof VehiclesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corridors': {
      id: '/corridors'
      path: '/corridors'
      fullPath: '/corridors'
      preLoaderRoute: typeof CorridorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field-reports': {
      id: '/field-reports'
      path: '/field-reports'
      fullPath: '/field-reports'
      preLoaderRoute: typeof FieldReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/route-engine': {
      id: '/route-engine'
      path: '/route-engine'
      fullPath: '/route-engine'
      preLoaderRoute: typeof RouteEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supply': {
      id: '/supply'
      path: '/supply'
      fullPath: '/supply'
      preLoaderRoute: typeof SupplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessibilityRoute: AccessibilityRoute,
  AlertsRoute: AlertsRoute,
  CorridorsRoute: CorridorsRoute,
  FieldReportsRoute: FieldReportsRoute,
  RouteEngineRoute: RouteEngineRoute,
  SupplyRoute: SupplyRoute,
  VehiclesRoute: VehiclesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
